name: Build Kernel

on:
  push:
    branches: [ A326BXXU1AUA5 ]
  pull_request:
    branches: [ A326BXXU1AUA5 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git bc bison build-essential curl flex gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libssl-dev libncurses5-dev
    - name: Build Kernel
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make a32x_defconfig
        make -j$(nproc)
